CREATE DATABASE [InternationalTransaction]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InternationalTransaction', FILENAME = N'C:\PRJ\trng\2c2p\github.com\onglityit\DBStorage\InternationalTransaction.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InternationalTransaction_log', FILENAME = N'C:\PRJ\trng\2c2p\github.com\onglityit\DBStorage\InternationalTransaction_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [InternationalTransaction] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [InternationalTransaction] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [InternationalTransaction] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [InternationalTransaction] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [InternationalTransaction] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [InternationalTransaction] SET ARITHABORT OFF 
GO
ALTER DATABASE [InternationalTransaction] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [InternationalTransaction] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [InternationalTransaction] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [InternationalTransaction] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [InternationalTransaction] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [InternationalTransaction] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [InternationalTransaction] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [InternationalTransaction] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [InternationalTransaction] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [InternationalTransaction] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [InternationalTransaction] SET  DISABLE_BROKER 
GO
ALTER DATABASE [InternationalTransaction] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [InternationalTransaction] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [InternationalTransaction] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [InternationalTransaction] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [InternationalTransaction] SET  READ_WRITE 
GO
ALTER DATABASE [InternationalTransaction] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [InternationalTransaction] SET  MULTI_USER 
GO
ALTER DATABASE [InternationalTransaction] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [InternationalTransaction] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [InternationalTransaction] SET DELAYED_DURABILITY = DISABLED 
GO
USE [InternationalTransaction]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [InternationalTransaction]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [InternationalTransaction] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
